bitcoin:
  type: object
  name: Bitcoin Settings
  description: RPC and P2P interface configuration options for Bitcoin Core
  nullable: false
  null-by-default: false
  spec:
    bitcoind-rpc:
      type: union
      name: Bitcoin Core RPC
      description: The Bitcoin Core node to connect to over the RPC interface
      tag:
        id: type
        name: Type
        variant-names:
          internal: Internal
          external: External
        description: |
          The Bitcoin Core node to connect to:
            - internal: The Bitcoin Core and Proxy services installed to your Embassy
            - external: An unpruned Bitcoin Core node running on a different device
      default: internal
      variants:
        internal:
          rpc-host:
            type: pointer
            name: Local RPC Address
            description: The LAN IP address of your Bitcoin Proxy service
            subtype: app
            app-id: btc-rpc-proxy
            target: lan-address
          rpc-user:
            type: pointer
            name: RPC Username
            description: The username for the RPC user allocated to BTCPay
            subtype: app
            app-id: btc-rpc-proxy
            target: config
            index: 'users.[first(item => ''item.name = "btcpayserver")].name'
          rpc-password:
            type: pointer
            name: RPC Password
            description: The password for the RPC user allocated to BTCPay
            subtype: app
            app-id: btc-rpc-proxy
            target: config
            index: 'users.[first(item => ''item.name = "btcpayserver")].password'
        external:
          connection-settings:
            type: union
            name: Connection Settings
            description: Information to connect to an external unpruned Bitcoin Core node
            tag:
              id: type
              name: Type
              description: |
                - Manual: Raw information for finding a Bitcoin Core node
                - Quick Connect: A Quick Connect URL for a Bitcoin Core node
              variant-names:
                manual: Manual
                quick-connect: Quick Connect
            default: quick-connect
            variants:
              manual:
                rpc-host:
                  type: string
                  name: Public Address
                  description: The public address of your Bitcoin Core server
                  nullable: false
                rpc-user:
                  type: string
                  name: RPC Username
                  description: The username for the RPC user on your Bitcoin Core RPC server
                  nullable: false
                rpc-password:
                  type: string
                  name: RPC Password
                  description: The password for the RPC user on your Bitcoin Core RPC server
                  nullable: false
                rpc-port:
                  type: number
                  name: RPC Port
                  description: The port that your Bitcoin Core RPC server is bound to
                  nullable: false
                  range: "[0,65535]"
                  integral: true
                  default: 8332
              quick-connect:
                quick-connect-url:
                  type: string
                  name: Quick Connect URL
                  description: |
                    The Quick Connect URL for your Bitcoin Core RPC server
                    NOTE: LND will not accept a .onion url for this option
                  nullable: false
                  pattern: 'btcstandup://[^:]*:[^@]*@[a-zA-Z0-9.-]+:[0-9]+(/(\?(label=.+)?)?)?'
                  patternDescription: Must be a valid Quick Connect URL. For help, check out https://github.com/BlockchainCommons/Gordian/blob/master/Docs/Quick-Connect-API.md
    bitcoind-p2p:
      type: union
      name: Bitcoin Core P2P
      description: The Bitcoin Core node to connect to over the P2P interface
      tag: type
      default: internal
      variants:
        internal:
          p2p-host:
            type: pointer
            name: Local P2P Address
            description: The LAN IP address of your Bitcoin service
            subtype: app
            app-id: bitcoind
            target: lan-address
        external:
          p2p-host:
            type: string
            name: Public Address
            description: The public address of your Bitcoin Core server
            nullable: false
          p2p-port:
            type: number
            name: P2P Port
            description: The port that your Bitcoin Core P2P server is bound to
            nullable: false
            range: "[0,65535]"
            integral: true
            default: 8333
lightning:
  type: union
  tag:
    id: type
    name: Type
    description: Enables BTCPay to use the selected internal lightning node.
    variant-names: 
      none: No selection
      c-lightning: C-Lightning
      lnd: LND
  name: Embassy Lightning Node
  description: Use this setting to grant BTCPay access to your Embassy's LND or c-lightning node. If you prefer to use an external Lightning node, or you do not intend to use Lightning, leave this setting blank. Please see the "Instructions" page for more details.
  default: none
  variants:
    none: {}
    lnd:
      connection-settings:
        type: pointer
        name: LND Local Address
        description: The LAN IP address of your Internal Lightning Network Daemon service
        subtype: app
        app-id: lnd
        target: lan-address
    c-lightning:
      connection-settings:
        type: pointer
        name: C-lightning Local Address
        description: The LAN IP address of your Internal C-Lightning service
        subtype: app
        app-id: c-lightning
        target: lan-address
