#!/command/with-contenv bash
# ^ allows access to the Docker container's environment variables

# -a  Mark variables which are modified or created for export
# -e  Exit immediately if a command exits with a non-zero status
set -ea

#  check readiness of altcoin connections if configured to use
monero_status=$(yq e '.altcoins.monero.status' /datadir/start9/config.yaml)
if [[ $monero_status = "enabled" ]] 
then
 MONERO_DIR=/datadir/btcpayserver/altcoins/monero
 mkdir -p $MONERO_DIR
 MONERO_UID=30236
 MONERO_GID=302340
 chown $MONERO_UID:$MONERO_GID $MONERO_DIR
 chmod 755 $MONERO_DIR
 CONF_FILENAME="monero-wallet-rpc.btcpayserver.conf"
 MONERO_BTCPAY_WALLET_RPC_CONF="${MONERO_DIR}/${CONF_FILENAME}"
 MONERO_BTCPAY_WALLET_RPC_PORT=18082
 #change directory to where the monero wallets, conf, rpc db file & logs dir will go and auth file can be written successfully
 cd "$MONERO_DIR"
 #remove old auth file in case it stuck around from an incomplete shutdown
 mwr_auth_file="monero-wallet-rpc.${MONERO_BTCPAY_WALLET_RPC_PORT}.login"
 if [ -f "$mwr_auth_file" ] ; then
  rm -f "$mwr_auth_file"
 fi

 #Ensure that the monero wallet directory exists
 MONERO_BTCPAY_WALLET_DIR=${MONERO_DIR}/wallets
 mkdir -p $MONERO_BTCPAY_WALLET_DIR
 chown $MONERO_UID:$MONERO_GID $MONERO_BTCPAY_WALLET_DIR
 chmod 775 $MONERO_BTCPAY_WALLET_DIR

 monero_daemon_rpc_credentials=""
 monero_daemon_rpc_username=$(yq e '.altcoins.monero.username' /datadir/start9/config.yaml)
 #If a monero daemon RPC username has been setup:
 if [ -n "$monero_daemon_rpc_username" ] && [ "$monero_daemon_rpc_username" != "null" ]
 then
   monero_daemon_rpc_password=$(yq e '.altcoins.monero.password' /datadir/start9/config.yaml)
   monero_daemon_rpc_credentials="daemon-login=$monero_daemon_rpc_username:$monero_daemon_rpc_password"
 fi

 #Construct a fully-formed monero-wallet-rpc config file from the template
 cp -f /etc/$CONF_FILENAME.template $MONERO_BTCPAY_WALLET_RPC_CONF
 sed -i "s|MONERO_DIR|$MONERO_DIR|g" $MONERO_BTCPAY_WALLET_RPC_CONF && \
 sed -i "s|MONERO_BTCPAY_WALLET_RPC_PORT|$MONERO_BTCPAY_WALLET_RPC_PORT|g" $MONERO_BTCPAY_WALLET_RPC_CONF && \
 sed -i "s|MONERO_BTCPAY_WALLET_DIR|$MONERO_BTCPAY_WALLET_DIR|g" $MONERO_BTCPAY_WALLET_RPC_CONF && \
 sed -i "s|MONERO_DAEMON_RPC_CREDENTIALS|$monero_daemon_rpc_credentials|g" $MONERO_BTCPAY_WALLET_RPC_CONF
 
 #Delay and try again if the wallet file is not already in place...
 while [[ ! -f "$MONERO_BTCPAY_WALLET_DIR/wallet" || ! -f "$MONERO_BTCPAY_WALLET_DIR/password" ]]
 do
  #Check again soon to see if the wallet file has been uploaded
  sleep 3
 done
 # start monero-wallet-rpc, copying stderr onto stdout
 exec s6-setuidgid $MONERO_UID:$MONERO_GID /usr/local/bin/monero-wallet-rpc --non-interactive --config-file $MONERO_BTCPAY_WALLET_RPC_CONF 2>&1

fi
