#!/command/with-contenv bash
# ^ allows access to the Docker container's environment variables

# -a  Mark variables which are modified or created for export
# -e  Exit immediately if a command exits with a non-zero status
set -ea

#  check readiness of monero connection if configured to use
altcoins=$(yq e '.altcoins.type' /datadir/start9/config.yaml)
if [[ $altcoins = "monero" ]]
then

  if test -d /mnt/monerod
  then
    # start monero-wallet-rpc, copying stderr onto stdout
    exec monero-wallet-rpc --rpc-bind-ip=0.0.0.0 --disable-rpc-login --confirm-external-bind --rpc-bind-port=18082 --non-interactive --trusted-daemon  --daemon-login=monero:_T9E17vFLSzRxUZCcHq3lX --daemon-address=https://monerod.embassy:18081 --wallet-file=/mnt/monerod/wallets/wallet --password-file=/mnt/monerod/wallets/password --tx-notify="/bin/sh ./notifier.sh -X GET http://btcpayserver.embassy:49392/monerolikedaemoncallback/tx?cryptoCode=xmr&hash=%s" 2>&1
  else
    echo "Monero mountpoint does not exist"
    exit 0
  fi
fi