- rule: "advanced.peers.listen?"
  description: Peer port must be listening on the network.
  suggestions:
    - SET:
        var: advanced.peers.listen
        to-value: true
- rule: '!(''[btcpayserver].bitcoin.bitcoind-rpc.type = "internal") OR ''[bitcoind].advanced.pruning.mode = "disabled"'
  description: Pruning must be disabled if internal Bitcoin Core node is being used without Bitcoin Proxy (ie. must be a full archival node)
  suggestions:
    - SET:
        var: 'advanced.pruning.mode'
        to-value: disabled