- rule: '''users.*.name = "btcpayserver"'
  description: 'Must have an RPC user named "btcpayserver"'
  suggestions:
    - PUSH:
        to: "users"
        value:
          name: btcpayserver
          allowed-calls: []
    - SET:
        var: 'users.[first(item => ''item.name = "btcpayserver")].password'
        to-entropy:
          charset: "a-z,A-Z,0-9"
          len: 22
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "getblock"'
  description: 'RPC user "btcpayserver" must have "getblock" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "getblock"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "getblockchaininfo"'
  description: 'RPC user "btcpayserver" must have "getblockchaininfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "getblockchaininfo"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "getnetworkinfo"'
  description: 'RPC user "btcpayserver" must have "getnetworkinfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "getnetworkinfo"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "getpeerinfo"'
  description: 'RPC user "btcpayserver" must have "getpeerinfo" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "getpeerinfo"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "getblockheader"'
  description: 'RPC user "btcpayserver" must have "getblockheader" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "getblockheader"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "setban"'
  description: 'RPC user "btcpayserver" must have "setban" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "setban"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "estimatesmartfee"'
  description: 'RPC user "btcpayserver" must have "estimatesmartfee" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "estimatesmartfee"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "getblockcount"'
  description: 'RPC user "btcpayserver" must have "getblockcount" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "getblockcount"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "sendrawtransaction"'
  description: 'RPC user "btcpayserver" must have "sendrawtransaction" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "sendrawtransaction"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "getrawtransaction"'
  description: 'RPC user "btcpayserver" must have "getrawtransaction" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "getrawtransaction"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "testmempoolaccept"'
  description: 'RPC user "btcpayserver" must have "testmempoolaccept" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "testmempoolaccept"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "utxoupdatepsbt"'
  description: 'RPC user "btcpayserver" must have "utxoupdatepsbt" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "utxoupdatepsbt"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "getbestblockhash"'
  description: 'RPC user "btcpayserver" must have "getbestblockhash" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "getbestblockhash"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "scantxoutset"'
  description: 'RPC user "btcpayserver" must have "scantxoutset" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "scantxoutset"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "signrawtransactionwithkey"'
  description: 'RPC user "btcpayserver" must have "signrawtransactionwithkey" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "signrawtransactionwithkey"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "generatetoaddress"'
  description: 'RPC user "btcpayserver" must have "generatetoaddress" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "generatetoaddress"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "validateaddress"'
  description: 'RPC user "btcpayserver" must have "validateaddress" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "validateaddress"
- rule: '''users.[first(item => ''item.name = "btcpayserver")].allowed-calls.* = "scantxoutset"'
  description: 'RPC user "btcpayserver" must have "scantxoutset" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "btcpayserver")].allowed-calls'
        value: "scantxoutset"
- rule: 'users.[first(item => ''item.name = "btcpayserver")].fetch-blocks?'
  description: RPC user "btcpayserver" must have "Fetch Blocks" enabled if bitcoind is a pruned node
  suggestions:
    - SET:
        var: 'users.[first(item => ''item.name = "btcpayserver")].fetch-blocks'
        to-value: true
