#!/command/with-contenv bash
# ^ allows access to the Docker container's environment variables

# -a  Mark variables which are modified or created for export
# -e  Exit immediately if a command exits with a non-zero status
set -ea

#  check readiness of lightning connections if configured to use
lightning_type=$(yq e '.lightning.type' /datadir/start9/config.yaml)
if [[ $lightning_type = "lnd" ]]
then

  if ! test -d /mnt/lnd
  then
    echo "LND mountpoint does not exist"
    exit 0
  fi

  while ! test -f /mnt/lnd/admin.macaroon
  do
    echo "Waiting for LND admin macaroon to be generated..."
    sleep 1
  done
fi

if [[ $lightning_type = "c-lightning" ]]
then

  if ! test -d /mnt/c-lightning
  then
    echo "Core Lightning mountpoint does not exist"
    exit 0
  fi

  while ! test -S /mnt/c-lightning/lightning-rpc
  do
    echo "Waiting for Core Lightning RPC socket..."
    sleep 1
  done
fi

#  check readiness of altcoin connections if configured to use
altcoins=$(yq e '.altcoins.type' /datadir/start9/config.yaml)
if [[ $altcoins = "monero" ]]
then

  if ! test -d /mnt/monerod
  then
    echo "Monero mountpoint does not exist"
    exit 0
  fi
fi

# configure templates and load environment variables generated for dependency connections 
configurator > .env 
source .env

/etc/init.d/nginx restart

# start btcpayserver, copying stderr onto stdout
exec dotnet /app/BTCPayServer.dll 2>&1